### ISSUE TITLE
404 Mega Issue

### ISSUE THREAD

**Issue by jonafato** [hyde/hyde.github.com#12]
Due to broken links on hyde.github.io, there have been several issues reported about 404s. This issue will be used track all of the broken links on the site and serve as a tracking issue for porting the missing documentation over to the Sphinx docs included with [hyde/hyde](/hyde/hyde).

Currently broken links:
- [ ] Site model documentation (#2)
- [ ] Configuration documentation source (#3)
- [ ] All of the screenshots on the homepage (#4)
- [ ] Pain points (#8, #11)
- [ ] Publishers (#9)
- [ ] Pages mentioned in comments on #8 and #9

This issue supersedes and closes #2, #3, #4, #8, #9, #11.

**Comment by hartwork** [comment]
I'm not sure if a mega/tracker ticket really makes fixing go faster: The barrier to start may appear higher.
It's three broken links in the first paragraph on the front page. That would be a good start for fixing in my eyes.
